name: Docker build and publish image

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]
jobs:
  docker-build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push app to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: .
          dockerfile: ./dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: docker.pkg.github.com
          repository: hovoh/relay3r-jobs/node
          tag_with_ref: true
